---
title: "Benchmarking"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Benchmarking}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(hermes6)
library(tibble)
library(magrittr)
```

Comparisons of speed for different Markov Smoking Probabilistic models.

Functions being tested are.
Creates list of functions where the name starts with markov. All top level functions should start with this.

```{r}
function_names <- ls("package:hermes6", pattern = "markov*")
function_names
```

```{r}
func_calls <- lapply(function_names, function(func) call(func))
```

```{r}
output <- lapply(function_names, function(func) {
  func_call <- call(func)
  print(func_call)
  out <- system.time(eval(func_call))
  print(out)
  out["elapsed"]
})
names(output) <- function_names
```

Benchmarking
```{r}
output_df <- output %>% 
  unlist(recursive = FALSE) %>% 
  enframe() 
output_df
```


